### ISSUE TITLE
Flush à cache

### ISSUE THREAD

**Issue by artikweb** [sousatg/auto-dns-config#3]
Após a alteração dos IP's do DNS, convém fazer um "Flush DNS" para limpar a cache do sistema.

**Comment by rafaelcpalmeida** [comment]
TO DO

**Comment by sousatg** [comment]
Adicionado commando ao script para windows para fazer o flush do DNS.

**Comment by sousatg** [comment]
@rafaelcpalmeida adiciona a mesma funcionalidade para mac quando puderes

**Comment by artikweb** [comment]
Bom trabalho! 5\* ;)
